name: OrangeHRM CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 18 * * *'    

jobs:
  test:
    runs-on: windows-latest

    env:
      DISCORD_WEBHOOK: ${{ secrets.ANONYMOUSONE }}
      REPORT_URL: https://sagarjhathi.github.io/anonymous-one/


    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'    



      - name: Notify Start
        run: |
          $body = @{
            content = "🚀 **CI STARTED**`nRepo: $env:GITHUB_REPOSITORY`nBranch: $env:GITHUB_REF_NAME`nRun: $env:GITHUB_RUN_ID"
          } | ConvertTo-Json -Depth 10
      
          Invoke-RestMethod -Uri $env:DISCORD_WEBHOOK -Method Post -Body $body -ContentType 'application/json'

      - name: Run Tests
        run: mvn clean test
        working-directory: booking.com



      - name: Notify Failure
        if: failure()
        run: |
          $body = @{
            content = "❌ **CI FAILED**`nRepo: $env:GITHUB_REPOSITORY`nBranch: $env:GITHUB_REF_NAME`nRun: $env:GITHUB_RUN_ID`nReport: $env:REPORT_URL"
          } | ConvertTo-Json -Depth 10
      
          Invoke-RestMethod -Uri $env:DISCORD_WEBHOOK -Method Post -Body $body -ContentType 'application/json'



      - name: Find latest run folder
        id: find_run
        run: |
           $runFolder = Get-ChildItem -Path "booking.com" -Directory -Filter "run_*" |
                         Sort-Object LastWriteTime -Descending |
                         Select-Object -First 1
        
            echo "RUN_FOLDER=$($runFolder.Name)" >> $env:GITHUB_ENV



      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: booking.com/${{ env.RUN_FOLDER }}


        # ✅ Save artifacts BEFORE switching branch
      # - name: Save artifacts
      #   run: |
      #     mkdir temp
      #     Copy-Item -Recurse -Force booking.com/logs temp/
      #     Copy-Item -Recurse -Force booking.com/screenshots temp/
      #     Copy-Item -Recurse -Force booking.com/reports temp/

      - name: Debug project structure
        run: |
           Get-ChildItem -Recurse -Directory


      - name: Save artifacts
        run: |
          $tempPath = "$env:RUNNER_TEMP\artifacts"
          $run = $env:RUN_FOLDER
      
          # Ensure temp exists
          New-Item -ItemType Directory -Path $tempPath -Force
      
          # Clean old
          Remove-Item -Recurse -Force "$tempPath/$run" -ErrorAction SilentlyContinue
      
          # Copy run folder
          Copy-Item -Recurse -Force "booking.com/$run" "$tempPath/"


      - name: Debug temp after save
        run: |
           Get-ChildItem "$env:RUNNER_TEMP\artifacts" -Recurse


# ✅ Now switch branch
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages



# ✅ 
      - name: Clean gh-pages
        run: |
           Get-ChildItem -Force | Where-Object { $_.Name -ne '.git' } | Remove-Item -Recurse -Force


      - name: Restore artifacts to gh-pages
        run: |
          $tempPath = "$env:RUNNER_TEMP\artifacts"
          $run = $env:RUN_FOLDER
      
          if (Test-Path "$tempPath/$run") {
              Copy-Item -Recurse -Force "$tempPath/$run" "."
          } else {
              Write-Host "Run folder not found in temp!"
              Get-ChildItem "$tempPath" -Recurse
              exit 1
          }

##
      - name: Set report path
        run: |
          $run = $env:RUN_FOLDER
          $reportPath = "$run/reports/ExtentReport.html"

          echo "REPORT_PATH=$reportPath" >> $env:GITHUB_ENV


          
      - name: Create index
        run: |
          $run = $env:RUN_FOLDER
          $reportPath = "$run/reports/ExtentReport.html"
      
          $content = "<meta http-equiv='refresh' content='0; url=$reportPath'>"
      
          Set-Content -Path index.html -Value $content


# ✅ Commit & push
      - name: Deploy
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "Update report" || echo "No changes"

          git push origin gh-pages --force

      - name: Notify Success
        if: success()
        run: |
          $body = @{
            content = "✅ **CI PASSED**`nRepo: $env:GITHUB_REPOSITORY`nBranch: $env:GITHUB_REF_NAME`nRun: $env:GITHUB_RUN_ID`nReport: $env:REPORT_URL"
          } | ConvertTo-Json -Depth 10
      
          Invoke-RestMethod -Uri $env:DISCORD_WEBHOOK -Method Post -Body $body -ContentType 'application/json'