name: OrangeHRM CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'    

      - name: Run Tests
        run: mvn clean test
        working-directory: booking.com

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/logs/
            **/reports/
            **/screenshots/


        # ✅ Save artifacts BEFORE switching branch
      - name: Save artifacts
        run: |
          mkdir temp
          Copy-Item -Recurse -Force booking.com/logs temp/
          Copy-Item -Recurse -Force booking.com/screenshots temp/
          Copy-Item -Recurse -Force booking.com/reports temp/

# ✅ Now switch branch
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

# ✅ Copy artifacts into gh-pages
      - name: Copy to gh-pages
        working-directory: gh-pages
        run: |
          Remove-Item -Recurse -Force gh-pages/* -ErrorAction SilentlyContinue
          Copy-Item -Recurse -Force ../temp/* .

# ✅ Create index.html
      - name: Create index.html
        working-directory: gh-pages   # ✅ IMPORTANT
        run: |
          $run = Get-ChildItem reports -Directory
          $runName = $run.Name

          Set-Content index.html "<meta http-equiv='refresh' content='0; url=reports/$runName/ExtentReport.html'>"


# ✅ Commit & push
      - name: Deploy
        working-directory: gh-pages
        run: |
           git checkout -B gh-pages

           git config user.name "github-actions"
           git config user.email "actions@github.com"

           git add .
           git commit -m "Update report" || echo "No changes"

           git push origin gh-pages --force